wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.21
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.8
    t:
      1:
      - 1
      - 9
      2:
      - 1
      - 9
      3:
      - 2
      4: 3.8.8
      5: 0.10.21
      8:
      - 1
      - 5
